name: Greet when a user opens first pull request

on:
  pull_request:
    types: [opened]
  
jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: "Kiitos ensimmäisestä Pull Requestistä!"
